---
name: clean_bloc_movies
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dartz: ^0.9.2
  equatable: ^1.2.5
  flutter_bloc: ^6.1.1
  flutter_svg: ^0.18.1
  get_it: ^5.0.1
  google_fonts: ^1.1.1
  http: ^0.12.2
  cached_network_image: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/pngs/
